version: '2'
services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:22.3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
volumes:
  clickhouse_data:
    driver: local
